// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaAPI.Data;

#nullable disable

namespace ProvaAPI.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20231211235913_Backend")]
    partial class Backend
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("ProvaAPI.Models.Aluno", b =>
                {
                    b.Property<int>("AlunoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataDeNascimento")
                        .HasColumnType("TEXT");

                    b.Property<int>("IMCId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("AlunoId");

                    b.HasIndex("IMCId");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            DataDeNascimento = "10 de Setembro de 2000",
                            IMCId = 1,
                            Nome = "xuxu beleza"
                        });
                });

            modelBuilder.Entity("ProvaAPI.Models.IMC", b =>
                {
                    b.Property<int>("IMCId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Altura")
                        .HasColumnType("REAL");

                    b.Property<string>("Classificacao")
                        .HasColumnType("TEXT");

                    b.Property<float>("Peso")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorImc")
                        .HasColumnType("REAL");

                    b.HasKey("IMCId");

                    b.ToTable("IMCs");

                    b.HasData(
                        new
                        {
                            IMCId = 1,
                            Altura = 115f,
                            Classificacao = "Magreza",
                            Peso = 0f,
                            ValorImc = 0f
                        });
                });

            modelBuilder.Entity("ProvaAPI.Models.Aluno", b =>
                {
                    b.HasOne("ProvaAPI.Models.IMC", "IMC")
                        .WithMany()
                        .HasForeignKey("IMCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IMC");
                });
#pragma warning restore 612, 618
        }
    }
}
